import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import LanguageProvider from "./LanguageProvider";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/main-sidebar/app-sidebar"
import AppHeader from "@/components/main-header/app-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { locale: "ar" | "en" };
}>) {
  const { locale } = await params;
  const isArabic = locale === "ar";

  return (
    <html lang={locale}
      dir={isArabic ? "rtl" : "ltr"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LanguageProvider>
          <SidebarProvider>
            <AppSidebar />

            <main className="w-full">
              <AppHeader />
              {children}
            </main>
          </SidebarProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}