import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import LanguageProvider from "../LanguageProvider";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/main-sidebar/app-sidebar"
import AppHeader from "@/components/main-header/app-header";
import { Toaster } from "@/components/ui/sonner"
import getCookies from "@/actions/getCookies";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getCookies("locale")
  const isRTL = locale?.value === "ar";

  return (
    <html lang={locale?.value}
      dir={isRTL ? "rtl" : "ltr"}
      suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LanguageProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <SidebarProvider>
              <AppSidebar dir={isRTL ? "rtl" : "ltr"}/>
              <main className="w-full">
                <AppHeader/>
                {children}
                <Toaster />
              </main>
            </SidebarProvider>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}