import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import LanguageProvider from "../LanguageProvider";
import { Toaster } from "@/components/ui/sonner"
import getCookies from "@/actions/getCookies";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getCookies("locale")
  const isRTL = locale?.value === "ar";

  return (
    <html lang={locale?.value}
      dir={isRTL ? "rtl" : "ltr"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LanguageProvider>
            <main className="w-full">
              {children}
              <Toaster />
            </main>
        </LanguageProvider>
      </body>
    </html>
  );
}